balderdashy/sails

- lib/hooks/blueprints/actions/remove.js
If you don't specify a child PK in the remove call (to remove an assocation), sails will crash. Example:
io.socket.delete('/user/1/pets/') // note the missing pet ID
Will result in:
```/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/associationMethods/remove.js:205
if(key.toString() !== '[object Object]') validAssociation = true;
^
TypeError: Cannot call method 'toString' of undefined
at Remove.validatePrimaryKey (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/associationMethods/remove.js:205:10)
at Remove.removeRecord (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/associationMethods/remove.js:133:34)
at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/assoc …
```
> catch undefined child pk in blueprints/remove

- lib/app/request.js
I found that when I try to call in test to an url with sails.request, the params were ignored:
```javascript
sails.request({
url: '/id-required',
method: 'post',
params: {
id: '1'
}
}, function(err, res, body){
if(err) return done(err);
body.status.should.be.equal(200);
return done();
});
```
The req.params.all() === {} in the controller. 
I fix it with just renaming the params var, and that's it!
> Fixed bug with sails.request params

- CHANGELOG.md
- lib/hooks/pubsub/index.js
Make sure the object (i.e Model) is clean in "publishUpdate", "message" methods.
For the "publishCreate" method, it seems like the code below is avoiding the error.
```JavaScript
var legacyData = _.cloneDeep({
verb: 'create',
data: values,
model: self.identity,
id: values[this.primaryKey]
});
```
> Fix #2636 RangeError: Maximum call stack size exceeded on PubSub hook

- lib/hooks/index.js
It seems like this dependency variable is unused since commit 3b77489c . Is this intentional or can it be removed?
> Remove unused dependency variable

- lib/hooks/http/initialize.js
sails sets it anyways. If someone disables sails' middleware for this header, they probably don't want express' either.
> disable express' built in `x-powered-by` header

- README.md
Don't know if this is actually used over Gitter. But I thought I'd fix it regardless?
> Fixed the Freenode link

- MODULES.md
Added link to [sails-generate-ember-blueprints](https://github.com/mphasize/sails-generate-ember-blueprints) to the community generators section.
> Add community generator for Ember blueprints

- package.json
- test/integration/hook.cors_csrf.test.js
- test/unit/router.bind.test.js
Today I decided to give io.js (v1.6.2) a try.
My project seems to be working fine, so I decided to run an `npm test` to test sails.
The issues I found were really very minor:
- microtime devDep v0.6.0 didn't compile right under io.js, so I updated it to the latest version, which uses the same API
- the HTTP OPTIONS string seems to be alphabetically sorted now, so I updated the tests accordingly (the supertest one could be done better though)
Hope this will be at least a minor help/thank you for making such a great project :)
P.S.: Congratulations on getting 10000 stars! :)
> Make sails compilable under io.js and pass the current test suite

- lib/router/req.js
for example if you posted data `{ isPirate: false }` and you run `req.param('isPirate')` from a controller, you'd get `undefined` returned as you didn't specify a `defaultValue` - so basically you couldn't post params that where === false. I think this edit captures the spirit of the OR guard used previously. If your happy with this, I would be ok with writing a test... if needed.
> req.param() is broken for boolean false params

- lib/hooks/moduleloader/index.js
Hi.
I added support for LiveScript. Even though #2122 seems like a better solution in the long run, it solves my needs. I didn't add support for scaffolding.
Is this something that you may find interesting to merge?
> Added LiveScript support

- bin/sails-deploy.js
We're currently passing an empty configuration to the sails deploy module. Obviously, we need to pass the actual configuration object.
> Pass configuration to sails deploy

- README.md
Hello,
Current link points to https://github.com/balderdashy/sails-docs/blob/master/FAQ.md#where-do-i-get-help while it should point to https://github.com/balderdashy/sails-docs/blob/master/FAQ.md#what-are-some-good-community-tutorials
Kind regards,
> Fix broken links to tutorials in the README.md

- lib/hooks/responses/defaults/badRequest.js
- lib/hooks/responses/defaults/forbidden.js
- lib/hooks/responses/defaults/notFound.js
- lib/hooks/responses/defaults/serverError.js
IMHO the current behavior in response handlers of clearing the body in production mode should be optional, hence the proposed `sails.config.keepResponseErrors` here.
Consider the case of a waterline validation error from a model backing a REST operation, one could return a 400 with a list of validation failures:
```
if (err && err.code === 'E_VALIDATION') {
return res.badRequest(err.invalidAttributes);
}
```
The docs [here](https://github.com/balderdashy/sails-docs/blob/master/concepts/Custom%20Responses/Custom%20Responses.md#resbadrequestvalidationerrors-redirectto) for `res.badRequest()`  say "For requesters expecting JSON, this response includes the 400 status code and any relevant data sent as validationErrors."  Well, this isn't true -- in production mode response body is cleared …
> Allows keeping response errors in production mode with sails.config.keepResponseErrors

- lib/preinstall_npmcheck.js
Hello,
I was about to install Sails for contribution, and when I tried to run `npm link` I got a "Unrecognized npm version" error. This happened on the preinstall script, and was due to my npm being a prerelease version (1.5.0-alpha-4, which by the way I should update). The npm engine requirement, though, is `>= 1.4.0` which should have resolved correctly... I guess...
Anyway, while fixing this issue I ended up doing a major rewrite of the preinstall script, which did not followed most syntax pattern of other scripts in the project.
> Get npm version fix

- lib/hooks/controllers/index.js
- add controllers to sails.controllers in any hook.configure method and
the controller definition will be loaded registered just as any bona
fide controller would
- individual controllers can also be extended by hooks, by adding
additional properties (actions) to a specific controller.
- cleaned up some extra spaces and old comments
@particlebanana please consider merging into 0.12 RC. Thanks.
> allow controllers to be added by hooks

- lib/hooks/controllers/index.js
- lib/hooks/services/index.js
- initialize sails.controllers namespace in hooks.controllers.configure (see #3083)
- initialize sails.services namespace in hooks.services.configure
- merge services with any pre-defined services
- code style cleanup
> allow services to be easily extended by hooks

- lib/hooks/grunt/index.js
The grunt process is being executed with its parents process arguments (i.e. `--debug`). This in turn causes a EADDRINUSE exception to occur.
Issue 
#2670 
Explanation
https://github.com/balderdashy/sails/issues/2670#issuecomment-92140615
> explicitly set fork args before grunt hook

- lib/hooks/blueprints/actions/update.js
might crash your connection provider. tested only on sails-mongo.
> update blueprint: prevent updating PK, but leave it for Model lifecycle callbacks

- lib/hooks/views/actions.js
- lib/hooks/views/configure.js
- lib/hooks/views/index.js
- lib/hooks/views/layoutshim.js
- closes #3041 
- `async` is way overused everywhere. removed occurrence from views hook
- de-fang missing `ejs` module warning
- reformatted to match the rest of the codebase
- use `_.isString` instead of `typeof`
> Views hook refactor

- lib/hooks/moduleloader/index.js
- cleaned up formatting
- set "hookName" in order to specify installable hook name.
e.g.
```
{
"sails": {
"isHook": true,
"hookName": "myHook"
}
}
```
> add "hookName" option to installable hook config

- lib/hooks/pubsub/index.js
- lib/hooks/services/index.js
- declare chronically un-declared "reverseAssociations" variable
- remove superfluous sails.services assignment
> cleaned up pubsub and services hooks

- lib/hooks/http/initialize.js
I added support for .pfx ssl certificates according to the node docs: http://nodejs.org/api/https.html#https_https_createserver_options_requestlistener
> Added support for ssl using a pfx certificate

- lib/hooks/moduleloader/index.js
- test/integration/fixtures/sampleapp/api/services/BasicService.js
- test/integration/fixtures/sampleapp/api/services/NoBindService.js
- test/integration/services.test.js
As per #2791, you cannot store classes in services since it automatically binds all the methods in the service to the service's context. This breaks the class system, obviously.
Since there's no way to programatically detect the intention of a function, either class or real function, we can't fix this is a seamless automatic way. Instead I added a new flag, "noBind", to use in those weird hyper specific corner cases such as this.
Test cases included.
> added "noBind" option to services to resolve #2791

- lib/hooks/blueprints/actionUtil.js
- lib/hooks/blueprints/actions/add.js
- lib/hooks/blueprints/actions/destroy.js
- lib/hooks/blueprints/actions/find.js
- lib/hooks/blueprints/actions/findOne.js
- lib/hooks/blueprints/actions/remove.js
- lib/hooks/blueprints/actions/update.js
Turns actionUtil.populateEach into 3 different functions that craves the way towards more reusable functions.
Our use case:
In certain specific scenarios [we want to publish actions](https://stackoverflow.com/questions/27254587/sails-publishupdate-system-does-not-propagate-to-associations) (publishUpdate et al.) to associated models (eg: User has Pets, when a pet changes, publish User update). We want to auto populate the associated models but where unable to use populateEach due its dependence on a `req` object. 
EDIT: next step would be exposing those helper function to userland somehow.
> pull apart actionUtil.populateEach to support reuse outside requests

- CHANGELOG.md
- bin/sails-console.js
This is a minor change that enables the useGlobal config option for REPL when running sails console.
I noticed that when using the sails autoreload hook that the available globals weren't being reloaded.  For example, I created a service called "Init" and when I made a change to my Init.js file, calling sails.services.init reflected the changes I made, but calling Init as a global on the console didn't.
Enabling the useGlobal option makes these changes available on the console when using the autoreload hook.
> Set useGlobal to true for REPL in sails console

- lib/router/req.js
These are methods in Express 3, and should be on the mock request for
consistency.
> Add .get() and .header() to MockReq

- lib/router/res.js
There seems to be a fairly critical bug where you can bring down a Sails instance by emitting a simple OPTIONS request over the socket.io REST interface (see the commit message for a more detailed description).
Steps to reproduce:
In a terminal:
```bash
$ sails new killme
$ cd killme
$ sails lift
```
In a browser's JS console (on localhost:1337):
```
> io.socket.request({method: 'options', url: '/anUndefinedRoute'});
```
> Stop OPTIONS requests over socket.io from crashing Sails

- README.md
This is a second PR of the same change. For some reason @mikermcneil just removed previously accepted PR on commit 5c3a23c6e8d4679cf28d3ed153c4fd85274f8155 with comment "removed broken badge". Actual badge isn't broken, only the dependencies that sails uses are outdated.
Imho isn't good policy to "hide" things like this...
> Added dependencies status image - take II

- lib/hooks/grunt/index.js
WebStorm IDE passes the ```--debug-brk=<PORTNUM>``` parameter to nodejs,
this breaks grunt hook, because the child nodejs process couldn't bind
the port already bound by current nodejs process.
See #2670 and #2888
> Really fix #2670

- lib/app/lower.js
This fixes a rare issue where the built-in `sails.log` object is overridden with a custom logging implementation which uses functions that depend on a particular value of `this`.
For example, if a `sails.log.verbose()` function is called like this:
```js
var log = sails.log.verbose
log(‘test message’)
```
The value of `this` within this function will be either `undefined` (strict mode) or the `global` object, instead of the expected `sails.log` object.
> For the sake of interest, I have replaced the logger with a [bunyan](https://github.com/trentm/node-bunyan) logger, which is implemented this way.
> Preserve context when calling log functions

- lib/EVENTS.md
- lib/router/bind.js
A small modification to include the route options in the object emitted by the `router:bind` event.
That would be very useful for hooks. It could replace (or maybe be used to implement?) the `sails.getRoutes()` method proposed [in the comments of PR-2659](https://github.com/balderdashy/sails/pull/2659#issuecomment-76107213).
Besides being useful for routing and debugging hooks, it could be used to generate api documentations like [Swagger](http://swagger.io/), [Raml](http://raml.org/) or [API Blueprint](https://apiblueprint.org/). For example, the [sails-swagger](https://github.com/tjwebb/sails-swagger) hook is kind of [reverse engineering the content of `sails.router._privateRouter.routes`](https://github.com/tjwebb/sails-swagger/blob/master/lib/xfmr.js) to find models associated to …
> Add the route options to the "routeObj" emited by the "router:bind" sails event

- lib/hooks/pubsub/index.js
As far as I can tell, `[association.alias]` is just creating an array with the alias value in it, and even `[undefined]` is truthy, so this will always pass.
Was this meant to check if `association.alias` is defined/truthy before using it in the accessor?
> Fix: Check for existence of association alias in pubsub

- lib/hooks/http/middleware/defaults.js
Not sure what if any tests should be updated for this.
> don't send stack track back for body parse errors when environment is production

- lib/hooks/blueprints/actions/update.js
Here's a quick fix for: https://github.com/balderdashy/sails/issues/2995, which doesn't return populated models on update if populate was set to false.
> "Update" blueprint honors model's "populate" configuration

- lib/hooks/blueprints/actionUtil.js
- lib/hooks/blueprints/actions/create.js
- lib/hooks/pubsub/index.js
- test/integration/router.APIScaffold.test.js
Fixes the issue balderdashy/sails#2977, which sails would convert an
array to an object and subsequently fail validation.
> Added support for JSON arrays

- lib/hooks/blueprints/index.js
- test/integration/fixtures/sampleapp/api/controllers/QuizController.js
- test/integration/fixtures/sampleapp/api/models/Quiz.js
- test/integration/router.APIScaffold.test.js
don't call `pluralize('/quiz')` (returns `/quizs`). call `pluralize('quiz')` (returns `quizzes`).
> Fix blueprints puralize option

- lib/app/lower.js
- lib/app/private/initialize.js
- test/integration/lift.lower.test.js
- test/unit/app.lower.test.js
Add and cleanup process event listeners properly.
Fixes warnings when doing lift/lower multiple times, e.g in before() and
after() functions in a test suite.
Tests:
test/integration/lift.lower.test.js
test/unit/app.lower.test.js
> Properly add/cleanup process event listeners.

- lib/hooks/moduleloader/index.js
This allows the hook names to be correctly parsed from modules published to npm under a user's namespace/scope - e.g. `@user/sails-hook-name`
Follows discussion in #3502
> [Patch] Update regex to parse hook names from module identities

- lib/hooks/moduleloader/index.js
Don't load the hook if it was marked as false on stable /cc @sgress454
> Don't load the hook if it was marked as false on stable

- lib/hooks/pubsub/index.js
Sails 0.12.0 deprecated sails.sockets.id() method. 
One of the core hooks pubsub still uses this method and triggers a warning
```
sails.sockets.id() is deprecated; use sails.sockets.getId().
```
This patch fixes the issue.
> fixed sails.sockets.id() is deprecated; use sails.sockets.getId() warning msg

- lib/hooks/http/middleware/defaults.js
- test/hooks/http/initialize.test.js
This basically removes most of the code from the `bodyParser` property of the object in `hooks/http/middleware/defaults.js`.  I think this code was written when Skipper was just getting started and needed a bit more handholding, but it probably hasn't worked for a long time.  It's _supposed_ to take the value of `sails.config.http.middleware.bodyParser`, validate it, and use it to get a body parser middleware function to use in the app.  But because all of the code in `defaults.js` is wrapped in a big `_.defaults(sails.config.http.middleware, {...}`, the function that gets returned is never used, since there's already something in `sails.config.http.middleware.bodyParser`.  The catch 22 is, an Express middleware function will _not_ pass the validation in `defaults.js`, so an error will be …
> [fixes #3592] allow sails.config.http.middleware.bodyParser config to work

- CHANGELOG.md
- lib/hooks/views/actions.js
- lib/hooks/views/onRoute.js
- lib/hooks/views/res.view.js
- test/integration/fixtures/sampleapp/views/app/index.ejs
- test/integration/fixtures/sampleapp/views/app/user/homepage.ejs
- test/integration/router.viewRendering.test.js
Now that `req.view` determines what to render based on what's in `req.options`, I don't see the utility of having a middleware function bound for each individual view, hence the removal of most of the code in `lib/hooks/views/action.js`.  If I'm missing something, lemme know.  Tests all pass without it though.  
Also added new tests for using the view target syntax (e.g. `'/foo': {view: 'foo/bar/baz'}`) and a test for the ability to do `'/foo': {view: 'foo'}` and have it render `views/foo/index.js` if it exists--not sure if that was ever documented, but the code was is in there so I made sure it still works.
> [Fixes #3604] Fix nested views

- lib/hooks/http/initialize.js
- test/integration/middleware.sails.test.js
Certain parts of the codebase - in particular the built is response functions (e.g. `res.serverError` etc) access `req._sails` to gain access to log functions. However, the setting of `req._sails` is currently bundled with the "request" hook, which contains potentially undesirable code - in particular around parsing `req.params.all()`, which can have a severe performance impact in certain situations - so may be disabled.
By setting `req._sails` by default on all requests we can ensure that the built in response helpers are usable indepenently of what intermediate hooks and middleware have loaded.
Fixes #3598
> Ensure req._sails is always set

- lib/hooks/views/configure.js
There is a long-standing open bug in consolidate - https://github.com/tj/consolidate.js/issues/143 - which causes errors in the callback functions passed to rendering methods to propogate back into the try/catch contained in consolidate and cause the callback to be fired twice. Since this bug has been open in consolidate for over two years, not much hope should be held of having it resolved there.
As such, add protection in Sails against errors in the callback functions being caught inside consolidate and the callback fired twice by forcing the callback to be called asynchronously.
Example:
```javascript
res.view('template', {}, function (e, result) {
if (e) {
// error thrown below causes callback to be fired twice and error caught here
}
throw new Error('error');
});
```
This can cause …
> [proposal] Force async-ness in template rendering methods

- lib/app/private/inspect.js
Sails.prototype.inspect() which is triggered by running something like `console.log(sails);` links to old docs page (http://links.sailsjs.org/docs) from 2 years ago which is now non-existant. This patch changes link to http://sailsjs.org/documentation/concepts/
> [patch] Sails.prototype.inspect() - fix link to docs

- bin/sails-console.js
- bin/sails-debug.js
- bin/sails-lift.js
- errors/fatal.js
- lib/app/lift.js
- package.json
- test/benchmarks/sails.load.test.js
Not sure if you want test with that
Fixes #3668
> [patch] Switch to chalk

- ROADMAP.md
I'm not entirely familiar with the submission process. If you notice something missing, or the issue does not follow the guidelines completely, I'll submit a corrected version as soon as possible. 
Sails CORS hooks are implemented in a way that differs a bit from the formal specification and can cause some undesired effects in certain enviroments. The primary cause are some blank headers set by Sails that should not be present as far as the aforementioned specification is concerned. While it doesn't matter in most cases, it may prevent other software that sits in from of the Node.js server from setting their own headers unless the CORS hook is disabled. In order to get a "sane" behavior, as well as minimizing the information one "attacker" may be able to obtain from a response, the …
> [proposal] ROADMAP.md: Add CORS proposal to backlog

- CHANGELOG.md
- lib/hooks/csrf/index.js
- package.json
- test/integration/hook.cors_csrf.test.js
Make `sails.config.csrf.routesDisabled` support RegExp, a partial solution of #2576 , because I think maybe the format of `/:id` is useless...
> [implements #2576] sails.config.csrf.routesDisabled support RegExp

- lib/hooks/views/render.js
After i18n upgrade (sails 0.12.2+), `sails.renderView()` no longer works when i18n hook is disabled, because it was never configured. This patch will skip `i18n.init()` when this hook was disabled.
Fixes #3742
> [fixes #3742] Fix render when i18n hook is disabled

- lib/hooks/policies/index.js
Default behaviour of `policy === false || policy === null` is to res.send(403).
This bypasses responses/forbidden.js and it's associated view.
> [patch] Use res.forbidden() instead of res.send(403)

- lib/app/private/initialize.js
Hello!
A coworker was getting some weird errors when he tried to lift a second app on a port that was already in use. It was odd to me that this error didn't propagate to the `err` parameter in the sails lift callback. After checking out the source, it appears that there was a typo in the final handler of `sails.runBootstrap`. Instead of receiving the `err` value from the async call on line 82, the `err` variable is instead referencing the one defined by `runBootstrap` on line 68.
I hope this helps!
> [patch] Fix err variable using parent scope because of mispelled parameter

- package.json
- test/integration/generate.test.js
- test/integration/helpers/appHelper.js
- test/integration/hook.3rdparty.test.js
- test/integration/hook.policies.test.js
- test/integration/hook.userconfig.test.js
- test/integration/hooks.user.test.js
- test/integration/new.test.js
- test/integration/www.test.js
Since `wrench` has been [officially deprecated](https://www.npmjs.com/package/wrench#warning-this-project-is-deprecated), I have removed it in favor of `fs-extras` which is already installed in the development dependencies.
I noticed there were several `TODO` comments mentioning that this should be done, and so here is a PR to do just that!
> [proposal] remove wrench from test runner requirements

- CONTRIBUTING.md
Two links for the documentation guidelines were actually referencing to the test directory of sails.
> [patch] Fixes wrong links in contribution guidelines

- lib/hooks/moduleloader/index.js
- package.json
Implements https://github.com/balderdashy/sails/pull/3142#issuecomment-247690755 (see also https://github.com/balderdashy/sails/pull/3142#issuecomment-247690755). This commit also adds TODOs re a deprecation warning for '.attributes.json' files, for switching to consistently using 'sails.config.paths.config', and for pulling out all built-in support for the 'configKey' hook property (and related documentation- see http://sailsjs.org/documentation/concepts/extending-sails/hooks/using-hooks#?changing-the-way-sails-loads-an-installable-hook). to [implements #3142] built-in server-side typescript support (+ literate iced babel coffee live everything)
> [implements #3142] built-in server-side typescript support (+ literate iced babel coffee live everything)

- lib/app/load.js
- lib/app/private/controller/README.md
- lib/app/private/controller/help-register-action.js
- lib/app/private/controller/index.js
- lib/app/private/controller/load-action-modules.js
- lib/app/private/controller/register-action.js
- lib/app/private/loadHooks.js
- lib/app/register-action-middleware.js
- lib/app/register-action.js
- lib/app/reload-actions.js
This fixes some assorted bugs that only show themselves when machine-as-action fails w/ an error.  It also adds a missing require, some missing comments, and then refactors the private registerAction function to `helpRegisterAction`, and `loadModules` to `loadActionModules`, for clarity.  And since they're private utilities, it also makes them stateless to match the way our other modern util functions are set up (in particular, removing their dependence on `this` context).   At this point, `sails._controller` should no longer be necessary, and can be removed (I may have missed old references to it though, so that'll need another pass to make sure).
> [patch] Fixes, comments, and clarifications in actions2 implementation.  This also stubs out some todos.

- lib/app/private/after.js
According to https://nodejs.org/api/events.html#events_emitter_emit_eventname_args, emit should return a boolean: true if the event had listeners, false otherwise.
Also clarified some docs.
> [patch] Make sails.emit 100% EventEmitter.emit compatible

- lib/hooks/http/get-configured-http-middleware-fns.js
- lib/hooks/responses/index.js
- lib/hooks/views/res.view.js
- lib/router/bindDefaultHandlers.js
- lib/router/index.js
- lib/router/res.js
Since 4.x, send(code, msg) has been deprecated. The current way of sending a code and a message is res.status(code).send(msg). Also, sending just a status code should use sendStatus
Check http://expressjs.com/en/4x/api.html#res.send, http://expressjs.com/en/4x/api.html#res.status and http://expressjs.com/en/4x/api.html#res.sendStatus for more info
> [patch] Fixes express 4.x deprecated messages when using send(code, msg)

- lib/hooks/http/start.js
When server starts longer than configurable `liftTimeout`, sails exists with this error from http hook:
>Server is taking a while to start up (it\'s been 4 seconds).'
"4 seconds" in this error message was hardcoded. This fix displays real listTimeout value in the error.
> [patch] Fix lift timeout error wording in http hook

- lib/app/configuration/load.js
This is to make it a little less painful to develop on an app with a bunch of dev data.  It **should (and can) only ever be used in development mode** (in production, it's always forced to `safe` anyway)
e.g. Here's how you can easily lift without waiting for Sails to drop and re-enter all records:
```
sails lift --safe
```
> ^^^This is useful when you know nothing has changed in `api/models/`, and when you know your development data is already valid.  
And e.g. here's how you can easily wipe out all dev data stored in your database(s):
```
sails lift --drop
```
> Currently, you can achieve the same effect by doing `sails lift --models.migrate=safe` and `sails lift --models.migrate=drop`... it's just a little awkward.  I don't know about you guys, but frankly it takes me like 30 seconds …
> Add shortcuts for common automigration settings.

- lib/hooks/grunt/index.js
In Node v6.3 the V8 Inspector was added to replace the Node remote debugger added in Node v4. To enable the V8 Inspector you need to pass the `--inspect` (or `--inspect-brk`) flag when launching your node application.
When using the grunt hook a new process is forked to run grunt.
The arguments passed in when lifting sails is passed on to the new fork which included the debug flags. In issue https://github.com/balderdashy/sails/issues/2670 a filter was added to remove the debug flags when spawning the fork however this filter only knew about the Node v4 flags and not the new V8 Inspector flags. The result is that if you try to use the V8 Inspector and the Grunt hook
the spawned process will launch with V8 Inspector and cause a port conflict on your app which also tries to start the V8 …
> [patch] Filter out the --inspect flag when launching grunt.

- lib/hooks/session/index.js
Given the verbose log level of the Redis error on L312, I'm assuming the errors on L320 and L327 were meant to be logged with a verbose log level as well. We're on Heroku and are getting hundreds of these errors which is flooding our Sentry logging as the Redis connections timeout every 300 seconds.
Another potential implementation would be to move the errors to an else block after the check for onRedisDisconnect and onRedisReconnect functions if the intent is for the onRedis... to provide custom overriding rather than supplemental logic.
Also fixing what I suspect is a typo on L324 where currently the logic checks for an onRedisDisconnect definition but then fires onRedisReconnect.
Lastly, changing _.extend ->_.merge on L440 to allow (in our case)  `saveUninitialized` to be set to false. …
> [patch] Enhancements to support Redis on Heroku

- lib/hooks/policies/index.js
Changed alwaysAllow function name to be alwaysAllow
> [patch] alwaysAllow function name should not be neverAllow

- lib/router/res.js
- test/unit/res.test.js
I couldn't find any existing test suite for the res.js file so hopefully the unit tests I wrote an in-keeping with the style of the project.
> [fixes #4445] don't clobber response content-type for JS object response

- lib/hooks/blueprints/actions/destroy.js
Updated the destroy blueprint action so that the meta query options from `parseBlueprintOptions` are passed into the actual call to `.destroy()`, since [`afterDestroy` only runs if `.meta({fetch: true})` is included](https://sailsjs.com/documentation/concepts/models-and-orm/lifecycle-callbacks#?lifecycle-callbacks-on-destroy). This makes the `afterDestroy` lifecycle callback still run by default when using the destroy blueprint action.
Fixes #5630
> [fixes #5630] Update destroy blueprint action so that `afterDestroy` lifecycle callbacks will still run by default

- lib/hooks/security/csrf/index.js
See https://github.com/balderdashy/sails/issues/6838
> [PATCH] IN CSRF hook, only lowercase the route path if the route isn't a regex

- lib/hooks/session/index.js
Fix for issue: https://github.com/balderdashy/sails/issues/6541.
The prefix was being included twice in the redis store.
> [fixes #6541]. omit prefix to avoid doubling up when key gets set

- lib/app/lift.js
Some lift errors (e.g. `sails-mysql` initialisation errors) include a `.raw` more details error
message which is important i.e. specific model errors which cannot be corrected without 
the message details. This change displays these messages if they are present.
Closes https://github.com/balderdashy/sails/issues/6965.
> [fixes #6965] Display underlying `raw` error on fail to lift app

- bin/sails.js
Currently when you run `sails new -h`, you get as part of the help output a reference to `--no-front-end` flag but actually the flag is `--no-frontend`
> [patch] change typo --no-front-end to --no-frontend in CLI flag help output

- bin/private/read-repl-history-and-start-transcribing.js
- lib/hooks/http/initialize.js
Fixes Node deprecation warnings [DEP0124](https://nodejs.org/api/deprecations.html#DEP0124) when the server starts, and [DEP0005](https://nodejs.org/api/deprecations.html#DEP0005) when starting the server with `sails console`
Tested in a new app with my local sails linked, everything worked as expected, no deprecation warnings.
> [patch] Fix node deprecation warnings

- docs/concepts/extending-sails/Adapters/adapterList.md
The update referenced in this note is available to read here -
https://node-postgres.com/announcements#2020-02-25
Without adding the new ssl connection attribute, database connection will fail.
> [proposal] Add documentation regarding a breaking change in SSL connection syntax

- package.json
This is done to fix the rogue colors package. Prompt@1.2.1 pins colors@1.4.0.
Issue: https://github.com/balderdashy/sails/issues/7201
> [fixes #7201] Bump up prompt to 1.2.1

- docs/concepts/Helpers/Helpers.md
Added 'Organizing helpers' section describing use of subfolders and additionally swapped all instances of `var` with `const` on the `helpers.md` page
> Update helpers.md docs to explain subfolders

- package.json
update expressjs to patched version to mitigate CVE-2022-24999 
fixes #7267
> bump expressjs to version 4.17.3

- README.md
Removed "Newsgroup" link due to lack of useage.
> Removed "Newsgroup" link

- .eslintrc
- lib/hooks/helpers/index.js
> [feat] Implement custom inspect on sails.helpers

- lib/app/lift.js
This fixes #7283 
Noticed we already had the logic to do this. This PR fixes a little issue on that logic that has to do with the check of `sails.config.ssl`.
I also updated the presentation and position of displaying the local URL as seen in the screenshot below.
> [fix] update logic to display local URL

- lib/router/req.js
Relevant for socket.io usage, and usage from tests.  (`sails.request()`)
> Improve virtual request parsing

- lib/hooks/pubsub/index.js
Adjusts for unnecessary `return true` pointed out in balderdashy/sails-hook-sockets#50, which will eventually no longer be a thing.  (Starting with the rps hook not using it.)
> RPS hook: Future-proof

- package.json
Changes:
Bumped versions of packages:
- Skipper: `^2.0.0` » `^2.0.5`
- captains-log: `^0.9.0-0` » `^9.0.4`
> Dependencies: bump `skipper` and `captains-log` versions

- package.json
Changes:
- upgraded the `ejs` dependency to 3.1.10
> Deps: bump `ejs` 3.1.7 » 3.1.10

- package.json
> Bump path-to-regexp to 1.9.0
