- lib/hooks/views/consolidate.js
Now user can override views path inside config.
> More correct root path for ect template engine.

- lib/hooks/logger/ship.js
```
info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.10.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `d:\wwwroot\tnm-corps\sails-tnmcorp`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.
```
> Sail boat cannot go without seagulls

- CHANGELOG.md
See https://github.com/balderdashy/sails/pull/2501
> Added restPrefix update to changelog

- lib/hooks/pubsub/index.js
Just standardizing the error messages.
> Typo in invalid usage error message

- lib/hooks/orm/backwards-compatibility/upgrade-model-definition.js
Attempt to fix https://github.com/sgress454/sails-hook-autoreload/issues/2
I think this is the right fix. Waterline isn't the issue. I would imagine renaming 'adapter' in the model object of Waterline to something else would be a much more involved pr.
```
{ identity: 'item_defaultoptions__option_items',
tableName: 'item_defaultoptions__option_items',
connection: 'MariaDB',
migrate: 'alter',
connections: { MariaDB: { config: [Object], _adapter: [Object], _collections: [Object] } },
waterline: 
{ _collections: 
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
_connections: {},
collections: 
{ category: [Object],
chitscreen: [Object],
item: [Object],
option: [Object],
optiongroup: [Object],
order: …
```
> shouldn't update connection with adapter if connection already exists!

- package.json
The version included in sails is too old, it lacks some functionality like `async.retry` etc.
> Update async dependency

- lib/router/req.js
same with this https://github.com/balderdashy/sails/pull/2511
> req param default value

- lib/app/private/bootstrap.js
- lib/hooks/cors/index.js
- lib/hooks/csrf/index.js
- lib/hooks/views/consolidate.js
- test/benchmarks/README.md
Found a few missing semicolons and corrected a few typos in comments/warnings.
> Cosmetic changes

- LICENSE.md
Only made 1 change:
1) Update LICENSE.md to include up-to-date year (2015)
No other changes were made.
> Update license with up-to-date year

- README.md
Updated link to Guillermo Rauch's github.
> Fixed broken github link

- 0.11-migration-guide.md
added missing ! on the link for extending sails doc
> added missing ! on link for extending sails doc

- lib/hooks/blueprints/actions/create.js
- fixes #2484 
@tjwebb Hopefully this helps.
> Fix issue #2484

- lib/hooks/blueprints/actions/update.js
Should fix it. :shipit: 
- resolves #2813
> #2813 clone the object to prevent circular references in the pubsub hook

- lib/hooks/moduleloader/index.js
> support npm private modules as hooks

- README.md
Was pointing to a broken page originally...
> Fixed getting started link in README

- lib/hooks/moduleloader/index.js
re: #3023: previous implementation was very limiting. only one module per namespace directory was loaded.
> fix npm nested module loader

- CONTRIBUTING.md
- README.md
small tweaks so these links are going to up to date docs.
> Link updates for docs

- lib/hooks/policies/index.js
- copy functions via re-bind rather than _.clone
- general formatting cleanup, retab
- initialize `this.middleware` in configure function
> Policies hook update

- .travis.yml
- lib/hooks/blueprints/index.js
- lib/hooks/index.js
- lib/hooks/orm/backwards-compatibility/upgrade-sails.config.js
- lib/hooks/pubsub/index.js
- lib/hooks/responses/defaults/badRequest.js
- lib/hooks/responses/defaults/created.js
- lib/hooks/responses/defaults/forbidden.js
- lib/hooks/responses/defaults/index.js
- lib/hooks/responses/defaults/notFound.js
- lib/hooks/responses/defaults/ok.js
- lib/hooks/responses/defaults/serverError.js
- lib/hooks/session/index.js
Using https://github.com/danielstjules/jsinspect
> Remove copy-pasted

- package.json
> Upgraded EJS to v2 from v0

- README.md
Reverts balderdashy/sails#3230
> Reverts balderdashy/sails#3230

- lib/hooks/grunt/index.js
In response to #2447, use a custom grunt task list based on NODE_ENV.  User simply needs to create a corresponding file name in tasks/register/.
> Look for custom grunt task file based on environment

- lib/hooks/responses/index.js
change error handling to fix #3273
> change error handling in res.jsonx

- test/integration/generate.test.js
- test/integration/helpers/appHelper.js
- test/integration/hook.3rdparty.test.js
- test/integration/lift.test.js
- test/integration/new.test.js
- test/integration/www.test.js
> Fix windows tests

- lib/hooks/orm/normalize-model.js
> fix connection loader

- CHANGELOG.md
> fixed typo

- ROADMAP.md
```
<script type="text/javascript">
window.SAILS_LOCALS = {
_csrf: <%- sails.htmlInject('_csrf') %>,
me: <%- sails.htmlInject('me') %>
};
</script>
```
So I need to access `me` from inside of an inline `<script>` tag on an HTML page (e.g. for bootstrapping data). This would replace any custom _recursive_ HTML escaping I currently have to do on the injected value (e.g. `<%- stringifyAndHtmlEscape(me) %>`), as well as a `typeof val==='undefined' check`.
> I have the option of using the `<%= %> EJS tags`, which evaluates, escapes and injects anything between the tags or the `<%- %> EJS tags` which evaluates and injects anything between the tags as-is. I want to use `<%- %>` but then I’m responsible for protecting against potentially malicious data passed in `me`. 
This...
```
<script …
```
> [Proposal] Handle untrusted bootstrap data in EJS

- test/mocha.opts
> [Patch] Remove needless require from mocha.opts

- lib/hooks/request/params.all.js
> [fixes #3723] Strip undefined keys from `req.params.all()`

- test/README.md
> [patch] Fixed a minor typo

- test/README.md
> [patch] Fixes typo

- lib/router/bindDefaultHandlers.js
https://github.com/balderdashy/sails/commit/203720432e89f4d0b1a1797940b03f97546213ac
> [patch] Fix for issue introduced in [2037204]

- package.json
see https://github.com/balderdashy/sails/issues/3872
> [fixes #3872] 0.12: bump express-session dep

- lib/hooks/moduleloader/index.js
this is re https://github.com/balderdashy/sails/issues/3884
> [fixes #3884] (or begins to anyway) - explicitly handle folder-style adapters

- lib/router/index.js
> [patch] update object=>dictionary, and add question about arrays & functions

- errors/warn.js
fixes #3901 
I fixed the mistyped variable names.  
I also used `requiredVersion` to follow the pattern in `incompatibleLocalSails()`
> [fixes #3901] fix mis typed variable names in badLocalDependency()

- test/helpers/test-spawning-sails-lift-child-process-in-cwd.js
Change the test timeout to 10 seconds. It errored with just 4. Also, fixed typo
> [patch] Change the test timeout to 10 seconds. It errored with just 4

- lib/hooks/security/README.md
- lib/hooks/security/cors/index.js
- lib/hooks/security/csrf/grant-csrf-token.js
- lib/hooks/security/csrf/index.js
Cleans up unused variables, some indentation here and there, and updates README.md. A better explanation should be added about CSRF
> [patch] Clean up code in security hook - Updated

- lib/hooks/blueprints/index.js
- test/hooks/blueprints/initialize.test.js
Adds support for PATCH HTTP method to REST blueprints.
E.g. JSON API spec requires a PATCH request to update a resource:
> A resource can be updated by sending a PATCH request to the URL that represents the resource.
> http://jsonapi.org/format/#crud-updating
> [proposal] Support PATCH for REST blueprints

- lib/app/private/initialize.js
Since Express 4, the router is built in, so middlewares are divided between pre-route and post-route. The way to tell when to do the split is via the ready event
> [proposal] Changed the emit('ready') comment, as it now is an important part of Sails

- lib/hooks/pubsub/index.js
> [fixes #4130] 	fix error when delete records without populate association

- bin/sails-debug-console.js
- bin/sails.js
This proposal adds a `debug-console` command to the Sails CLI, essentially a hybrid of the existing `console` and `debug` commands. This lifts a Sails app in debug mode, allowing interactive debugging from the console.
I use the `sails console` command extensively to test my models, services, etc... It's one of my favorite aspects of Sails development. Having an app lifted with both the console and debugger attached allows me to invoke methods and debug them on the fly. I find it very powerful. I hope others will, too!
It's a fairly simple addition. The only thing I had an issue with was passing the program options (silent, verbose, silly) to the newly spawned debug process. I solved it by using a global variable, but I'm hoping someone else has a better idea...
> [proposal] Add a command for lifting the sails console in debug mode.

- .github/ISSUE_TEMPLATE
What do you think about asking for adapter info and version?
Several times I see that being asked on issues, or that confusion happens because of things working for one adapter but not in an other one.
As always, my 2 cents.
> [patch] Add adapter info to Issues template

- package.json
> [patch] solve npm 5.4.2 install issue

- bin/sails-console.js
This is the proposed solution for the issue #4198.
> [fixes #4198] Changed the way the app exits with sails console. 

- test/.eslintrc
You don't need to set explicit globals, you can just use env: mocha
> [PATCH] Configure mocha environment for setting global functions in eslint for the tests

- bin/sails-run.js
```js
sails run foo
```
…checks for a shell script definition:
• first at `package.json`, for a shell command under the `foo` key in your NPM `scripts: {}`
• then at `scripts/foo.js`
• and finally at `scripts/foo.js`
Also needs to support:
```js
sails run @bazhq/foo
```
> [proposal] Extend sails-run to also look for installable commands.

- bin/sails.js
> [PATCH] Adds  --staging to lift help

- .travis.yml
- bin/sails-migrate.js
- bin/sails.js
- lib/hooks/moduleloader/index.js
- lib/hooks/userhooks/index.js
> [implements `sails migrate`]

- CHANGELOG.md
> [patch] Updated contributors

- MODULES.md
> [fixes typo] filesystem in MODULES.md

- package.json
Update version of i18n-2 from 0.6.3 to 0.7.3 to solve the following problem derivates from dependencies of this package:
deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
> [patch]Update package.json changed the i18n-2 version

- lib/hooks/blueprints/actions/update.js
This is a simple fix for issue #6824
> [fixes #6824] wrap the record id in a array when subscribing

- README.md
> [misc] Team information update as requested

- package.json
Fix vulnerability: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
Fixes balderdashy/sails#6962
> [fixes #6962] Upgrade minimist

- docs/anatomy/tasks/config/sails-linker.js.md
some typo errors
1. wrote specified twice
2. calso instead of also
3. you'd like them to be included
> [proposal] sails-linker.js.md

- docs/reference/application/advanced-usage/sails.registerActionMiddleware.md
Change "under-the-hook" to "under-the-hood".
> [patch] Small text correction

- bin/sails-run.js
> Fix typo in sails-run.js

- package.json
`sort-route-addresses@^0.0.3` -> `sort-route-addresses@^0.0.4`
> [misc] Upgrade sort-route-addresses dependency

- docs/reference/sails.config/sails.config.session.md
Added a section about using the `__Host-` prefix
> Docs: Update session config docs

- lib/router/req.js
#7297  #7292
Changes:
- Updated req.js to fix a bug introduced in https://github.com/balderdashy/sails/commit/4a023dc5095a4b30fdc8535f705ed34cd22d2f7d.
> Fix #7297 &  #7292

- package.json
Changes:
- upgraded `express`: `4.17.3` » `4.19.2`
> Upgrade express

- package.json
Changes:
- bumped @sailshq/lodash: `^3.10.2` » `^3.10.6`
> Dependencies: bump @sailshq/lodash version

- package.json
Changes:
- Bumped express to `4.21.2`
> [deps] Bump express
